- hosts: all
  remote_user: root
  vars:
    java_install_folder: /usr/share
    file_name: jdk-8u261-linux-x64.tar.gz
  tasks:
    - name: copy jdk
      copy:
        src=/opt/software/{{ file_name }}
        dest={{ java_install_folder }}

    - name: tar jdk
      shell:
        chdir={{ java_install_folder }}
        tar zxf {{ file_name }}

    - name: set JAVA_HOME
      blockinfile:
        path: /root/.zshrc
        marker: "#{mark} JDK ENV"
        block: |
          JAVA_HOME={{ java_install_folder }}/jdk1.8.0_261
          JRE_HOME=$JAVA_HOME/jre
          PATH=$PATH:$JAVA_HOME/bin
          CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
          export JAVA_HOME
          export JRE_HOME
          export PATH
          export CLASSPATH

    - name: source zshrc
      shell: source /root/.zshrc

    - name: remove tar.gz file
      file:
        path: "{{ java_install_folder }}/{{ file_name }}"
        state: absent
