- hosts: all
  remote_user: root
  tasks:
    - name: remove the mariadb
      yum:
        name: mariadb
        state: absent

    - debug:
        msg: "这里使用清华源：https://mirrors.tuna.tsinghua.edu.cn/help/mysql/"

    - name: create repo file
      file:
        path="/etc/yum.repos.d/{{ item }}"
        state=touch
      with_items:
        - mysql-community.repo

    - name: set repo file
      blockinfile:
        path: /etc/yum.repos.d/mysql-community.repo
        marker: ""
        block: |
          [mysql-connectors-community]
          name=MySQL Connectors Community
          baseurl=https://mirrors.tuna.tsinghua.edu.cn/mysql/yum/mysql-connectors-community-el7-$basearch/
          enabled=1
          gpgcheck=1
          gpgkey=https://repo.mysql.com/RPM-GPG-KEY-mysql

          [mysql-tools-community]
          name=MySQL Tools Community
          baseurl=https://mirrors.tuna.tsinghua.edu.cn/mysql/yum/mysql-tools-community-el7-$basearch/
          enabled=1
          gpgcheck=1
          gpgkey=https://repo.mysql.com/RPM-GPG-KEY-mysql

          [mysql-5.7-community]
          name=MySQL 5.7 Community Server
          baseurl=https://mirrors.tuna.tsinghua.edu.cn/mysql/yum/mysql-5.7-community-el7-$basearch/
          enabled=1
          gpgcheck=1
          gpgkey=https://repo.mysql.com/RPM-GPG-KEY-mysql


    - name : install mysql 2
      yum:
        name: mysql-community-server.x86_64
      async : 1000
      poll : 0
      register: mysql_install_result

    - name: 'check install result'
      async_status: jid={{ mysql_install_result.ansible_job_id }}
      register: job_mysql_install_result
      until: job_mysql_install_result.finished
      retries: 600

    - name: rename conf file
      shell: "{{ item }}"
      with_items:
        - mv /etc/my.cnf /etc/my.cnf.back

    - name: create my.cnf file
      file:
        path="/etc/{{ item }}"
        state=touch
      with_items:
        - my.cnf

    - name: set my.cnf
      blockinfile:
        path: /etc/my.cnf
        marker: ""
        block: |
          [mysql]
          default-character-set = utf8mb4
          [mysqld]
          max_connections = 500
          datadir = /var/lib/mysql
          socket = /var/lib/mysql/mysql.sock
          bind-address = 127.0.0.1
          symbolic-links=0
          log-error=/var/log/mysqld.log
          pid-file=/var/run/mysqld/mysqld.pid
          default-storage-engine = InnoDB
          collation-server = utf8mb4_unicode_520_ci
          init_connect = 'SET NAMES utf8mb4'
          character-set-server = utf8mb4
          lower_case_table_names = 1
          max_allowed_packet = 50M
          sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

    - name: enable mysql
      shell: "{{ item }}"
      with_items:
         - systemctl enable mysqld.service
         - systemctl restart mysqld.service
         - cat /var/log/mysqld.log | grep password
    - debug:
        msg: "读取默认生成的密码：cat /var/log/mysqld.log | grep password"
    - debug:
        msg: "进入客户端：mysql -uroot -p 输入生成的密码"
    - debug:
        msg: "修改密码并永不过期（必须是大小写字母+特殊符号+数字）：ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY 'Meek_123456' PASSWORD EXPIRE NEVER;"
    - debug:
        msg: "创建用户：CREATE USER 'myuser'@'%' IDENTIFIED WITH 'mysql_native_password' BY 'MyPwd_123456';"
    - debug:
        msg: "修改密码并永不过期：ALTER USER 'myuser'@'%' IDENTIFIED WITH 'mysql_native_password' BY 'MyPwd_123456' PASSWORD EXPIRE NEVER;"
    - debug:
        msg: "分配所有数据库权限：GRANT ALL PRIVILEGES ON *.* TO 'myuser'@'%' WITH GRANT OPTION;"
    - debug:
        msg: "分配单个数据库权限：GRANT ALL PRIVILEGES ON myDbName1.* TO 'myuser'@'%' WITH GRANT OPTION;"
    - debug:
        msg: "刷新配置：FLUSH PRIVILEGES;"
